Retrieve scale files from registry
loopholelabs/scale pull request #41
Opened 2023-02-02 23:49 UTC by SuperManifolds

Previously known as pulldown (https://github.com/loopholelabs/scale/pull/33)

2023-02-03 14:22 UTC, jimmyaxod commented
Thanks for taking this over @SuperManifolds

2023-02-10 02:06 UTC, ShivanshVij requested changes
Looks good but needs some changes

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +func WithApiKey(apiKey string) Option {
`WithAPIKey(apiKey string)`

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +		cacheDirectory: "~/.cache/scale/functions",
save this in a const or use the homedir lib (https://pkg.go.dev/github.com/mitchellh/go-homedir) to get this?

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +		apiBaseUrl:     "https://api.scale.sh/v1",
const as well

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +// TODO: We should use the hash in the filename for optimization
we should probably do this now rather than later

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +		return err
Check if already exists

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +		return err
os.IsExist or something

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +type GetFunctionResponse struct {
We should probably use a swagger-generated client if we can here, but this is fine for now

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +	client := &http.Client{}
Let's use http.DefaultClient here

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry.go
> +	response := &GetFunctionResponse{}
response := new(GetFunctionResponse)

2023-02-10 02:06 UTC, ShivanshVij commented on go/registry/registry_test.go
> +		WithBaseUrl("https://api.dev.scale.sh/v1"),
Const or set via env as well?

2023-02-10 02:06 UTC, ShivanshVij commented on ts/src/registry/index.test.ts
> +        WithApiBaseUrl("https://api.dev.scale.sh/v1"),
const or set via env too?

2023-02-10 02:06 UTC, ShivanshVij commented on ts/src/registry/index.ts
> +    cacheDirectory: "~/.cache/scale/functions",
Some way to use the homedir lib here too? The `~` won't work on some operating systems.

2023-02-10 02:06 UTC, ShivanshVij commented on ts/src/registry/index.ts
> +    apiBaseUrl: "https://api.scale.sh/v1",
const

2023-02-10 02:06 UTC, ShivanshVij commented on ts/src/registry/index.ts
> +function buildFilename(func: string, tag: string, config: Config): string {
Hash in the filename here too

2023-02-10 02:06 UTC, ShivanshVij commented on ts/src/registry/index.ts
> +      response.on('error', (error) => {
Does this trigger if the response code isn't 200?

2023-02-16 05:19 UTC, merged